# Generated by Django 4.1 on 2022-08-25 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myname',
            name='email',
            field=models.EmailField(default=True, max_length=200),
        ),
    ]
