# Generated by Django 4.1 on 2022-08-30 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first', '0002_myname_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myname',
            name='email',
        ),
        migrations.RemoveField(
            model_name='myname',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myname',
            name='last_name',
        ),
        migrations.AddField(
            model_name='myname',
            name='author',
            field=models.ForeignKey(default='enter full name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myname',
            name='content',
            field=models.TextField(default='enter content'),
        ),
        migrations.AddField(
            model_name='myname',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='myname',
            name='title',
            field=models.CharField(default='enter title', max_length=100),
        ),
    ]
