# Generated by Django 4.1 on 2022-09-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myname',
            name='content',
        ),
    ]
