# Generated by Django 4.1 on 2022-09-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0003_myname_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myimg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='myname',
            name='profile_pic',
        ),
    ]
